language: csharp
mono: none
dotnet: 2.0.3

install:
- ./install.sh

script:
  - ./build.sh
  - ./test.sh
  
deploy:
  provider: script
  script: ./deploy.sh  
  on:
    branch: release  
    tags: true